# Numpy Practice 

### Do The following :
- Finish the practice
- share it on your github account

#### Write the code that will produce the requested output or action as you see on the following cell

In [9]:
## For example 
## to get the output Hello, Mohammed
print("Hello, Mohammed") ## TODO

Hello, Mohammed


In [1]:
x = print("Hello, my name is 'jack'")
x

Hello, my name is 'jack'


### import the package numpy and make the shortcut "np" for it. 

In [2]:
## TODO

!pip install numpy
import numpy as np

#### define a numpy array [1, 2, 3, 4, 5] and assign it to variable x 

In [3]:
## TODO

x = np.array([1,2,3,4,5])

### Print x 

In [4]:
## TODO 
print (x)

[1 2 3 4 5]


### Print the mean of x using numpy 

In [5]:
## TODO
"The mean of the array is:",x.mean()

('The mean of the array is:', 3.0)

### Print the maximum number in array x

In [6]:
## TODO 
"the maximum number of the array is:",x.max()

('the maximum number of the array is:', 5)

### Generate a random number between 35 and 40

In [7]:
## TODO 
#pick intger number or float numbers 
#by Removing the '#'
rng = np.random.default_rng()

#rng.random.uniform(35,40) # float

np.random.randint(35,40)  # int

38

### generate a list (N) of 1000 numbers with random values between 100 and 150  

In [8]:
## TODO 
#pick intger number or float numbers 
#by Removing the '#'

# N = rng.random.uniform(low = 100, high = 150, size= 1000) # float

N = np.random.randint(100,150,size =(1000))                # int

N

array([139, 147, 113, 134, 108, 128, 116, 130, 140, 142, 137, 146, 103,
       104, 117, 112, 126, 104, 107, 142, 130, 123, 122, 105, 119, 141,
       119, 134, 100, 147, 131, 113, 142, 100, 144, 147, 104, 126, 124,
       122, 101, 148, 109, 107, 111, 137, 109, 104, 135, 112, 136, 127,
       144, 116, 133, 119, 119, 108, 107, 109, 130, 127, 148, 120, 131,
       102, 103, 126, 101, 116, 123, 133, 105, 139, 128, 105, 129, 117,
       127, 147, 118, 114, 120, 137, 117, 106, 121, 121, 149, 105, 139,
       115, 129, 129, 113, 106, 104, 142, 103, 100, 136, 113, 145, 148,
       145, 124, 132, 114, 138, 109, 138, 114, 127, 109, 148, 106, 117,
       117, 139, 100, 119, 142, 138, 115, 123, 110, 137, 144, 132, 118,
       111, 102, 149, 114, 149, 101, 102, 125, 129, 102, 125, 121, 110,
       103, 101, 127, 119, 105, 115, 137, 126, 121, 144, 113, 131, 126,
       138, 102, 111, 115, 149, 114, 141, 140, 140, 139, 126, 129, 104,
       145, 105, 136, 131, 132, 110, 114, 138, 122, 147, 111, 12

### get the mean, median, std, and variance of the list N 

In [9]:
## TODO 
print('The Mean is', np.mean(N))
print('The Median is',np.median(N))
print('The std is',N.std())
print('The variance is',np.var(N))

The Mean is 124.596
The Median is 125.0
The std is 14.653354018790372
The variance is 214.72078399999995


### generate a 2D array of size 3 x 4 of random numbers between 18-65 

In [10]:
##TODO 
#pick intger number or float numbers 
#by Removing the '#'


D2 = np.random.randint(18,65,size=(3,4)) #int

#D2 = rng.uniform(low=18, high=65, size=(3,4)) #float

D2

array([[36, 53, 47, 48],
       [63, 51, 55, 53],
       [21, 34, 40, 43]])

### Get the mean for every columns N

In [11]:
## TODO
# axis for colums is 0
# axis for rows is 1
C = D2.mean(axis = 0)
print(f'This is the First column  {C[0]}') 

print(f'This is the Second column {C[1]}')

print(f'This is the Thered column {C[2]}')

D2

This is the First column  40.0
This is the Second column 46.0
This is the Thered column 47.333333333333336


array([[36, 53, 47, 48],
       [63, 51, 55, 53],
       [21, 34, 40, 43]])

### Get the mean for every row of N 


In [12]:
## TODO
# axis for colums is 0
# axis for rows is 1
R = D2.mean(axis = 1)
print(f'This is the First row  {R[0]}') 

print(f'This is the Second row {R[1]}')

print(f'This is the Thered row {R[2]}')

D2

This is the First row  46.0
This is the Second row 55.5
This is the Thered row 34.5


array([[36, 53, 47, 48],
       [63, 51, 55, 53],
       [21, 34, 40, 43]])

### Create the following 2D array (S) of students grade in a classroom
- grades [coursework, midterm exam, final exam]
- [20, 15, 40]
- [25, 24, 35]
- [21, 15, 25]

In [13]:
## TODO

S = np.array([[20, 15, 40],[25, 24, 35],[21, 15, 25],])

#G = np.array(['coursework', 'midterm exam', 'final exam'])

S

array([[20, 15, 40],
       [25, 24, 35],
       [21, 15, 25]])

### Get the sums of student grades in S

In [14]:
## TODO
# axis for colums is 0
# axis for rows is 1
grade = S.sum(axis = 1)

print('Student 1 =',grade[0])
print('Student 2 =',grade[1])
print('Student 3 =',grade[2])

Student 1 = 75
Student 2 = 84
Student 3 = 61


### Get the means of student grades in every activity (coursework, midterm exam, final exam) in S

In [15]:
## TODO
# axis for colums is 0
# axis for rows is 1
activity = S.mean(axis = 0)

print(f"This is the Mean of Coursework {activity[0]}")
print(f"This is the Mean of Midterm exam {activity[1]}")
print(f"This is the Mean of Final exam {activity[2]}")
S

This is the Mean of Coursework 22.0
This is the Mean of Midterm exam 18.0
This is the Mean of Final exam 33.333333333333336


array([[20, 15, 40],
       [25, 24, 35],
       [21, 15, 25]])

### reshape S in a way that make the colums represent the students and rows represent the activity, as follow
- [20, 25, 21] 
- [15, 24, 15]
- [40, 35, 25]

In [16]:
## TODO
b = S.transpose()
#print("testoutput",b.mean(axis=1)[0])
#print("testoutput",b.mean(axis=1)[1])
#print("testoutput",b.mean(axis=1)[2])
b

array([[20, 25, 21],
       [15, 24, 15],
       [40, 35, 25]])

# Pandas Practice 

### import the package pandas and make the shortcut "pd" for it. 

In [17]:
## TODO
!pip install pandas
import pandas as pd

### create Series call it (Data) with the values 'a','b','d','u' and 'I'

In [18]:
## TODO

data = ['a','b','d','u','I']
data

['a', 'b', 'd', 'u', 'I']

### change index to 3,6,9,12, and 15 for (data) 

In [19]:
## TODO

index = [3,6,9,12,15]
changer = pd.Series(data,index)
changer

3     a
6     b
9     d
12    u
15    I
dtype: object

### change index to client1, client2, client3, client4 and client5 for (data) 

In [20]:
## TODO 
pd.Series(data,index=['client1','client2','client3','client4','client5',])

client1    a
client2    b
client3    d
client4    u
client5    I
dtype: object

### create a dataframe (D) with the followin values
- 	Name -	Age
-   Ali	 -  55
- 	Ahmad -	15
- 	Nora -	40

### Get the means of ages of people in (D)

In [21]:
## TODO expected value is 36.66
#D = pd.DataFrame([['Ali',55],["Ahmad",15],['Nora',40]],columns=['Name','Age'])

name=['Ali','Ahmad','Nora']
age = [55,15,40]
D = pd.DataFrame({'Name':name,'Age':age})

D

Name  Age
0    Ali   55
1  Ahmad   15
2   Nora   40

In [22]:
D.mean()

Age    36.666667
dtype: float64